Question 1

In [15]:
import numpy as np

In [7]:
arr = np.arange(2,50,3)

In [8]:
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [10]:
print(type(arr))

<class 'numpy.ndarray'>


Question 2

In [24]:
a=[]*5
for i in range(5):
    a.append(input("Enter next element in first list : "))

Enter next element in first list : 3
Enter next element in first list : sutanu
Enter next element in first list : 2
Enter next element in first list : apple
Enter next element in first list : 4


In [76]:
b=[]*5
for i in range(5):
    b.append(input("Enter next element in second list : "))

Enter next element in second list : 5
Enter next element in second list : 9
Enter next element in second list : boat
Enter next element in second list : apple
Enter next element in second list : 4


In [77]:
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
b

['5', '9', 'boat', 'apple', '4']

In [79]:
a_arr=np.array(a)

In [80]:
b_arr=np.array(b)

In [81]:
c=np.concatenate((a_arr, b_arr), axis=0)

In [82]:
print(c)

['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '5' '9' 'boat' 'apple' '4']


In [83]:
a_arr.sort()

In [84]:
a_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
b_arr.sort()
b_arr

array(['4', '5', '9', 'apple', 'boat'], dtype='<U5')

Question 3

In [41]:
def array_prop(array):
    print(array.ndim)
    print(array.shape)

In [42]:
array_prop(a_arr)

1
(5,)


Question 4

In [45]:
a = np.arange(10)

In [46]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
a[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [49]:
a.shape

(10,)

In [50]:
a[:, np.newaxis].shape

(10, 1)

In [51]:
a[np.newaxis, :]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [52]:
a[np.newaxis, :].shape

(1, 10)

In [54]:
a[np.newaxis, :, np.newaxis]

array([[[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]])

In [55]:
a[np.newaxis, :, np.newaxis].shape

(1, 10, 1)

In [56]:
b=np.expand_dims(a, axis=0)

In [57]:
b

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [58]:
b.shape

(1, 10)

In [59]:
b=np.expand_dims(a, axis=1)

In [60]:
b

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [61]:
b.shape

(10, 1)

Question 5

In [67]:
arr = np.random.randn( 3,3 )
arr

array([[-1.06126085, -1.3195152 ,  2.29353043],
       [ 1.42875198,  0.12800982,  1.07456148],
       [ 0.10252097,  0.69845822, -1.74419999]])

In [72]:
brr=np.random.randn( 3,3 )
brr

array([[-1.35031696,  0.83087294,  0.36900826],
       [-1.36522148, -0.72106651, -0.05719387],
       [ 1.24140771,  0.45762465, -0.00846518]])

In [73]:
np.vstack((arr,brr))

array([[-1.06126085, -1.3195152 ,  2.29353043],
       [ 1.42875198,  0.12800982,  1.07456148],
       [ 0.10252097,  0.69845822, -1.74419999],
       [-1.35031696,  0.83087294,  0.36900826],
       [-1.36522148, -0.72106651, -0.05719387],
       [ 1.24140771,  0.45762465, -0.00846518]])

In [74]:
np.hstack((arr,brr))

array([[-1.06126085, -1.3195152 ,  2.29353043, -1.35031696,  0.83087294,
         0.36900826],
       [ 1.42875198,  0.12800982,  1.07456148, -1.36522148, -0.72106651,
        -0.05719387],
       [ 0.10252097,  0.69845822, -1.74419999,  1.24140771,  0.45762465,
        -0.00846518]])

Question 6

In [1]:
a=input ("Length of the array : ")

Length of the array : 5


In [2]:
len=int(a)


In [11]:
arr=[]
for i in range(len):
    arr.append(int(input("Enter element : ")))

Enter element : 6
Enter element : 7
Enter element : 6
Enter element : 2
Enter element : 1


In [5]:
print(type(arr))

<class 'list'>


In [6]:
from collections import Counter

In [12]:
Counter(arr).keys()

dict_keys([6, 7, 2, 1])

In [13]:
Counter(arr).values()

dict_values([2, 1, 1, 1])

Alternative

In [16]:
values, counts = np.unique(arr, return_counts=True)

In [18]:
values


array([1, 2, 6, 7])

In [19]:
counts

array([1, 1, 2, 1], dtype=int64)